#!/bin/bash

echo "🔧 GitHub Secrets 設定助手"
echo "=========================="
echo ""

echo "📋 需要設定的 GitHub Secrets："
echo ""
echo "🔹 Vercel 相關："
echo "   - VERCEL_TOKEN"
echo "   - VERCEL_ORG_ID" 
echo "   - VERCEL_PROJECT_ID"
echo ""
echo "🔹 Cloudflare 相關："
echo "   - CLOUDFLARE_ZONE_ID"
echo "   - CLOUDFLARE_API_TOKEN"
echo ""
echo "🔹 應用程式相關："
echo "   - VITE_FIREBASE_API_KEY"
echo "   - VITE_FIREBASE_AUTH_DOMAIN"
echo "   - VITE_FIREBASE_PROJECT_ID"
echo "   - VITE_FIREBASE_APP_ID"
echo "   - VITE_GTM_ID"
echo "   - GEMINI_API_KEY"
echo ""

echo "🌐 GitHub Repository URL："
echo "https://github.com/simona940301-tech/plus-web-monorepo/settings/secrets/actions"
echo ""

echo "📝 設定步驟："
echo "1. 點擊上方連結進入 GitHub Secrets 頁面"
echo "2. 點擊 'New repository secret'"
echo "3. 逐一新增上述所有 secrets"
echo "4. 完成後執行測試部署"
echo ""

echo "🔑 如何取得各項資訊："
echo ""
echo "Vercel Token:"
echo "  → https://vercel.com/account/tokens"
echo "  → 點擊 'Create Token'"
echo ""
echo "Vercel Org/Project ID:"
echo "  → https://vercel.com/dashboard"
echo "  → 選擇專案 → Settings → General"
echo ""
echo "Cloudflare Zone ID:"
echo "  → https://dash.cloudflare.com/"
echo "  → 選擇網域 → Overview"
echo ""
echo "Cloudflare API Token:"
echo "  → https://dash.cloudflare.com/profile/api-tokens"
echo "  → 點擊 'Create Token'"
echo "  → 選擇 'Custom token'"
echo "  → 權限：Zone:Zone:Read, Zone:Cache Purge:Edit"
echo ""

read -p "按 Enter 繼續設定..."
